# Generated by Django 3.1.5 on 2021-01-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aranjament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'aranjamente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('iddisciplina', models.PositiveBigIntegerField(db_column='iddisciplina', primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('idelev', models.PositiveBigIntegerField(db_column='idelev', primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=35)),
                ('prenume', models.CharField(max_length=35)),
                ('an', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'elevi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idprofesor', models.PositiveBigIntegerField(db_column='idprofesor', primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=35)),
                ('prenume', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'profesori',
                'managed': False,
            },
        ),
    ]
